### ISSUE TITLE
create a basic layout for each screen

### ISSUE THREAD

**Issue by MohHajri** [DIN21SP-MobileDevProject/PatkatAppAndroid#3]
deciding on the overall structure of each screen, such as where buttons, text boxes, and other UI elements will be located using Android Studio's layout editor

STEPS:

- creating a basic layout for each screen. the layout should include the overall structure of the screen, such as the location of buttons, text boxes, and other UI elements.

- adding UI elements to the screen. This includes things like buttons, text boxes, labels, images, and other components.

- Customizing UI elements: This includes changing the font size and style, adjusting the color scheme

**Comment by ni9iri** [comment]
We should create some common Composables for these screens. Such as BottomNavbar and Navbar
